name: Build and Publish Docker Image using Dagger
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: "Repository name with owner"
      image:
        required: true
        type: string 
        description: "Name of docker image"
      ref:
        required: true
        type: string
        description: "The branch, tag, or SHA to checkout"
      dockerfile:
        required: true
        type: string
        description: "Location of the Dockerfile"
      namespace:
        type: string
        default: dictybase
        description: "Namespace to use for the Docker image"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dagger repo with justfile 
        uses: actions/checkout@v4
        with: 
          repository: dictybase-docker/dagger-of-dcr
          ref: develop
      - name: setup just binary
        uses: extractions/setup-just@v2
        with:
          just-version: 1.28.0
      - name: build and publish docker image
        id: publish
        run: just build-publish-image ${{ inputs.repository }} ${{ inputs.ref }} ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKER_PASS }} ${{ inputs.namespace }} ${{ inputs.image }} ${{ inputs.dockerfile }}
 
