name: Build and Publish Docker Image using Dagger
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: "Repository name with owner"
      image:
        required: true
        type: string 
        description: "Name of docker image"
      ref:
        required: true
        type: string
        description: "The branch, tag, or SHA to checkout"
      dockerfile:
        required: true
        type: string
        description: "Location of the Dockerfile"
      namespace:
        type: string
        default: dictybase
        description: "Namespace to use for the Docker image"
      dagger_ref:
        type: string
        default: develop
        description: "Git ref of dictybase-docker/dagger-of-dcr to checkout"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env:
      JUST_UNSTABLE: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout dagger repo with justfile 
        uses: actions/checkout@v4
        with: 
          repository: dictybase-docker/dagger-of-dcr
          ref: ${{ inputs.dagger_ref }}
      - name: setup just binary
        uses: extractions/setup-just@v4
        with:
          just-version: 1.58.0
      - name: build and publish docker image
        id: publish
        run: |
          just build-publish-image \
            --repository ${{ inputs.repository }} \
            --ref ${{ inputs.ref }} \
            --user ${{ secrets.DOCKERHUB_USER }} \
            --pass ${{ secrets.DOCKER_PASS }} \
            --namespace ${{ inputs.namespace }} \
            --image ${{ inputs.image }} \
            --dockerfile ${{ inputs.dockerfile }}
 
