name: Composite deploy for backend workflow

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
        description: backend application to be deployed, should be one of content, annotation, order or stock
      repository:
        required: true
        type: string
        description: "Repository name with owner"
      image:
        required: true
        type: string 
        description: "Name of docker image"
      ref:
        required: true
        type: string
        description: "The branch, tag, or SHA to checkout"
      dockerfile:
        required: true
        type: string
        description: "Location of the Dockerfile"
      cluster:
        required: true
        type: string
        description: "name of kubernetes cluster"
      cluster_state_storage:
        required: true
        type: string
        description: "location of cluster state"
      artifact_name:
        default: kubectl-config
        type: string
        description: "Name of the artifact to delete"
      kubectl_config_file:
        type: string
        default: dictycr.yaml
        description: "Name of the kubectl config file"
      stack:
        type: string
        default: dev
        description: "Name of the Pulumi stack to use"

jobs:
  # Setup Dagger binary and cache
  # Outputs:
  # - dagger_version: The version of the Dagger binary
  # - dagger_checksum: The checksum of the Dagger binary
  dagger-setup:
    uses: ./.github/workflows/dagger-setup.yaml

  # Build and publish Docker image
  # Outputs:
  # - image_tag: The tag of the published Docker image
  build-publish-image:
    needs: dagger-setup
    uses: ./.github/workflows/build-publish-image.yaml
    secrets: inherit
    with:
      repository: ${{ inputs.repository }}
      image: ${{ inputs.image }}
      ref: ${{ inputs.ref }}
      dockerfile: ${{ inputs.dockerfile }}
      dagger_version: ${{ needs.dagger-setup.outputs.dagger_version }}
      dagger_checksum: ${{ needs.dagger-setup.outputs.dagger_checksum }}

  # Setup deployment environment
  # Outputs:
  # - workflow_run_id: The ID of the GitHub workflow run
  deploy-setup:
    needs: dagger-setup
    uses: ./.github/workflows/deploy-setup.yaml
    secrets: inherit
    with:
      cluster: ${{ inputs.cluster }}
      cluster_state_storage: ${{ inputs.cluster_state_storage }}
      dagger_version: ${{ needs.dagger-setup.outputs.dagger_version }}
      dagger_checksum: ${{ needs.dagger-setup.outputs.dagger_checksum }}
      artifact_name: ${{ inputs.artifact_name }}
      kubectl_config_file: ${{ inputs.kubectl_config_file }}

  # Deploy backend application
  # No outputs
  deploy-backend:
    needs: [dagger-setup, build-publish-image, deploy-setup]
    uses: ./.github/workflows/deploy-backend.yaml
    secrets: inherit
    with:
      run_id: ${{ needs.deploy-setup.outputs.workflow_run_id }}
      dagger_version: ${{ needs.dagger-setup.outputs.dagger_version }}
      dagger_checksum: ${{ needs.dagger-setup.outputs.dagger_checksum }}
      image_tag: ${{ needs.build-publish-image.outputs.image_tag }}
      app: ${{ inputs.app }}
      artifact_name: ${{ inputs.artifact_name }}
      kubectl_config_file: ${{ inputs.kubectl_config_file }}
      stack: ${{ inputs.stack }}

  # Delete kubectl artifact
  # No outputs
  delete-artifact:
    needs: deploy-backend
    uses: ./.github/workflows/delete-artifact.yaml
    with:
      artifact_name: ${{ inputs.artifact_name }}



