name: lint-golang
on: 
  workflow_call:
    inputs:
      repository:
        description: "The name of the repository from which the slash command was dispatched"
        required: true
        type: string
      ref:
        required: true
        type: string
        description: "The branch,tag or SHA to checkout"
      version:
        type: string
        description: "golanglint-ci version"
        default: "v1.64.8-alpine"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dagger repo with justfile 
        uses: actions/checkout@v4
        with: 
          repository: dictybase-docker/dagger-of-dcr
          ref: develop
      - name: setup just binary
        uses: extractions/setup-just@v2
        with:
          just-version: 1.36.0
      - name: run lint
        run: just lint-repo ${{ inputs.repository }} ${{ inputs.ref }} ${{ inputs.version }}
