name: Setup Dagger Binary and Cache
on:
  workflow_call:
    inputs:
      dagger_path:
        required: true
        type: string
        description: path where dagger binary will be kept
    outputs:
      dagger_checksum:
        description: "The checksum of the Dagger binary"
        value: ${{ jobs.setup-dagger.outputs.dagger_checksum }}
      dagger_version:
        description: "The version of the Dagger binary"
        value: ${{ jobs.setup-dagger.outputs.dagger_version }}

env:
  ACTION_BIN_PATH: /tmp/github_actions/bin

jobs:
  setup-dagger:
    runs-on: ubuntu-latest
    outputs:
      dagger_checksum: ${{ steps.dag_check.outputs.dagger_bin_checksum }}
      dagger_version: ${{ steps.dag_check.outputs.dagger_version }}
    steps:
      - name: manage paths
        run: |
          mkdir -p $ACTION_BIN_PATH ${{ inputs.dagger_path }}
          echo $ACTION_BIN_PATH >> $GITHUB_PATH
          echo ${{ inputs.dagger_path }} >> $GITHUB_PATH

      - name: download and setup path for github actions binary
        run: |
          curl -L -o ${ACTION_BIN_PATH}/actions \
            https://github.com/dictybase-docker/github-actions/releases/download/v2.8.0/action_2.8.0_linux_amd64
          chmod +x ${ACTION_BIN_PATH}/actions

      - name: setup dagger version and checksum
        id: dag_check
        run: actions sc

      - name: try to restore dagger binary cache with dagger version and checksum
        id: restore_dagger_bin_cache
        uses: actions/cache@v4
        with: 
          path: ${{ inputs.dagger_path }}
          key: ${{ runner.os }}-${{ steps.dag_check.outputs.dagger_version}}-${{ steps.dag_check.outputs.dagger_bin_checksum }}

      - if: steps.restore_dagger_bin_cache.outputs.cache-hit != 'true'
        name: install dagger if the bin cache not restored
        id: dag_install
        run: actions sd --dagger-version ${{ steps.dag_check.outputs.dagger_version }} --dagger-bin-dir ${{ inputs.dagger_path }}
