name: Test Deploy

on:
  push:
    branches:
      - develop

env:
  DAGGER_BIN_PATH: /tmp/dag/bin

jobs:
  setup-dagger:
    uses: ./.github/workflows/setup-dagger.yaml
    with:
      dagger_path: ${{ env.DAGGER_BIN_PATH }}

  deploy-setup:
    needs: setup-dagger
    uses: ./.github/workflows/deploy-setup.yaml
    secrets: inherit
    with:
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}

  deploy-backend:
    needs: deploy-setup
    uses: ./.github/workflows/deploy-backend.yaml
    secrets: inherit
    with:
      run_id: ${{ needs.deploy-setup.outputs.workflow_run_id }}

