name: Test Deploy setup
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-setup.yaml
    secrets: inherit
    with:
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
