name: Test Deploy

on:
  push:
    branches:
      - develop

jobs:
  setup-dagger:
    uses: ./.github/workflows/dagger-setup.yaml

  build-publish-image:
    needs: setup-dagger
    uses: ./.github/workflows/build-publish-image.yaml
    secrets: inherit
    with:
      repository: dictyBase/static-server.git
      image: goran
      ref: develop
      dockerfile: Dockerfile
      namespace: cybersiddhu
      dagger_version: ${{ needs.setup-dagger.outputs.dagger_version }}
      dagger_checksum: ${{ needs.setup-dagger.outputs.dagger_checksum }}

  deploy-setup:
    needs: setup-dagger
    uses: ./.github/workflows/deploy-setup.yaml
    secrets: inherit
    with:
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      dagger_version: ${{ needs.setup-dagger.outputs.dagger_version }}
      dagger_checksum: ${{ needs.setup-dagger.outputs.dagger_checksum }}

  deploy-backend:
    needs: [setup-dagger, build-publish-image, deploy-setup]
    uses: ./.github/workflows/deploy-backend.yaml
    secrets: inherit
    with:
      run_id: ${{ needs.deploy-setup.outputs.workflow_run_id }}
      dagger_version: ${{ needs.setup-dagger.outputs.dagger_version }}
      dagger_checksum: ${{ needs.setup-dagger.outputs.dagger_checksum }}
