name: Test Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy-setup:
    uses: ./.github/workflows/deploy-setup.yaml
    secrets: inherit
    with:
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
  deploy-backend:
    secrets: inherit
    uses: ./.github/workflows/deploy-backend.yaml
    needs: deploy-setup
    with:
      run_id: ${{ needs.deploy-setup.outputs.workflow_run_id }}
