name: Test Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yaml
    secrets: inherit
    with:
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      repository: dictyBase/static-server.git
      image: goran
      ref: develop
      dockerfile: Dockerfile
      namespace: cybersiddhu
