name: Test Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yaml
    with:
      cluster: secrets.DEV_STAGING_CLUSTER 
      cluster_state_storage: ${{ secrets.DEV_STAGING_KOPS_STATE_STORAGE }}
      repository: "https://github.com/dictyBase/static-server.git"
      image: goran
      ref: 5041b41
      dockerfile: Dockerfile
      namespace: cybersiddhu
