name: Test Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy-setup:
    uses: ./.github/workflows/deploy-app.yaml
    with:
      cluster: ${{ secrets.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ secrets.DEV_STAGING_KOPS_STATE_STORAGE }}
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yaml
